#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.
#
# Writes .omp/LOCAL_ENVIRONMENT.md, the description of this machine's tools, generated by
# probing them. .omp/AGENTS.md (the portable project context) is maintained by hand and is
# never written here; the script only warns if it is missing or does not include the
# generated file.
#
# Usage: ./setup_machine_context.sh [machine-name]      (default: debian-home)
#
# The compiler/runtime validation facilities (warnings, ASan, UBSan, TSan) are not assumed:
# each is verified by compiling and running a small program with g++ and clang++, and only the
# outcome is reported.

set -euo pipefail

MACHINE_NAME="${1:-debian-home}"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OMP_DIR="$REPO_ROOT/.omp"
AGENTS_FILE="$OMP_DIR/AGENTS.md"
LOCAL_ENV_FILE="$OMP_DIR/LOCAL_ENVIRONMENT.md"
GITIGNORE="$REPO_ROOT/.gitignore"

# fbc is not on PATH; the project tools find it the same way (tools/toolchain/fbc.py).
FBC_DEFAULT="$HOME/Downloads/FreeBASIC-1.10.1-linux-x86_64/bin/fbc"
FBC="${GEF_FBC:-$FBC_DEFAULT}"
FBC_TARBALL="$(dirname "$(dirname "$FBC")").tar.gz"

mkdir -p "$OMP_DIR"

PROBE_DIR="$(mktemp -d)"
trap 'rm -rf "$PROBE_DIR"' EXIT

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

command_path() {
    command -v "$1" 2>/dev/null || printf 'not available'
}

first_line() {
    "$@" 2>/dev/null | head -n 1 || true
}

tool_section() {
    local label="$1"
    local command_name="$2"
    shift 2

    local path
    path="$(command_path "$command_name")"

    printf -- "- %s\n" "$label"

    if [[ "$path" == "not available" ]]; then
        printf "  - Status: not available\n"
    else
        printf "  - Command: \`%s\`\n" "$command_name"
        printf "  - Path: \`%s\`\n" "$path"

        local version
        version="$(first_line "$@")"

        if [[ -n "$version" ]]; then
            printf "  - Version: \`%s\`\n" "$version"
        fi
    fi
}

# Probe programs. The TSan probe starts a thread, so the TSan runtime is exercised for real;
# the clean probes must run without any sanitizer report.
cat > "$PROBE_DIR/plain.cpp" <<'EOF'
#include <cstdio>
int main() { std::puts("ok"); return 0; }
EOF
cat > "$PROBE_DIR/threads.cpp" <<'EOF'
#include <atomic>
#include <thread>
std::atomic<int> counter{0};
int main() {
    std::thread worker([] { for (int i = 0; i < 10000; ++i) { ++counter; } });
    for (int i = 0; i < 10000; ++i) { ++counter; }
    worker.join();
    return counter == 20000 ? 0 : 1;
}
EOF

# probe COMPILER SOURCE FLAGS...: compile and run; succeed only if both work cleanly.
probe() {
    local compiler="$1" source="$2"
    shift 2
    local exe="$PROBE_DIR/probe_$$_$RANDOM"
    command -v "$compiler" >/dev/null 2>&1 || return 1
    "$compiler" -std=c++23 "$@" "$PROBE_DIR/$source" -o "$exe" >/dev/null 2>&1 || return 1
    "$exe" >/dev/null 2>"$exe.err" || return 1
    ! grep -q 'Sanitizer' "$exe.err"
}

# validation_item LABEL SOURCE FLAGS...: one bullet with the compilers that passed the probe.
validation_item() {
    local label="$1" source="$2"
    shift 2
    local ok=() failed=() compiler
    for compiler in g++ clang++; do
        if probe "$compiler" "$source" "$@"; then
            ok+=("$compiler")
        else
            failed+=("$compiler")
        fi
    done
    printf -- "- %s:\n" "$label"
    printf "  - \`%s\`\n" "$*"
    if ((${#ok[@]})); then
        printf "  - Verified with: %s\n" "$(printf '`%s` ' "${ok[@]}" | sed 's/ $//')"
    fi
    if ((${#failed[@]})); then
        printf "  - **Not working with:** %s\n" "$(printf '`%s` ' "${failed[@]}" | sed 's/ $//')"
    fi
}

# ---------------------------------------------------------------------------
# Machine-local environment description
# ---------------------------------------------------------------------------

{
    echo "# Local Development Environment"
    echo
    echo "> This file is machine-specific and should not be committed to Git."
    echo

    echo "## Machine"
    echo
    echo "- Machine name: \`$MACHINE_NAME\`"
    echo "- Hostname: \`$(hostname)\`"
    echo "- Architecture: \`$(uname -m)\`"
    echo "- Kernel: \`$(uname -sr)\`"

    if [[ -f /etc/os-release ]]; then
        # shellcheck disable=SC1091
        source /etc/os-release
        echo "- Operating system: \`${PRETTY_NAME:-unknown}\`"
    fi

    echo "- Shell: \`${SHELL:-unknown}\`"
    echo "- Repository root: \`$REPO_ROOT\`"
    echo

    echo "## OMP"
    echo
    tool_section "OMP" omp omp --version
    echo "- Project OMP directory: \`.omp/\`"
    echo "- Project LSP configuration: \`.omp/lsp.json\`"
    echo "- Project session directory: \`.omp/sessions/\`"
    echo "- Local environment file: \`.omp/LOCAL_ENVIRONMENT.md\`"
    echo

    echo "## Python"
    echo
    tool_section "Python" python3 python3 --version
    echo
    tool_section "basedpyright" basedpyright basedpyright --version
    echo
    tool_section "Ruff" ruff ruff --version
    echo
    tool_section "pytest" pytest pytest --version
    echo

    echo "## C and C++"
    echo
    tool_section "GCC" gcc gcc --version
    echo
    tool_section "G++" g++ g++ --version
    echo
    tool_section "Clang" clang clang --version
    echo
    tool_section "Clang++" clang++ clang++ --version
    echo
    tool_section "clangd" clangd clangd --version
    echo
    tool_section "clang-tidy" clang-tidy sh -c 'clang-tidy --version | grep -m1 -i version | sed "s/^ *//"'
    echo
    tool_section "clang-format" clang-format clang-format --version
    echo
    tool_section "CMake" cmake cmake --version
    echo
    tool_section "CTest" ctest ctest --version
    echo
    tool_section "Ninja" ninja ninja --version
    echo
    tool_section "Universal Ctags" ctags ctags --version
    echo
    tool_section "GDB" gdb gdb --version
    echo
    tool_section "GNU patch" patch patch --version
    echo
    echo "- glibc"
    echo "  - Version: \`$(first_line ldd --version)\`"
    echo

    echo "### Compiler/runtime validation"
    echo
    echo "Each facility below was verified when this file was generated: a small program was"
    echo "compiled with the flags and run, with no diagnostic. The TSan probe runs two threads."
    echo
    validation_item "Compiler warnings" plain.cpp -Wall -Wextra -Wpedantic -Werror
    validation_item "AddressSanitizer" plain.cpp -fsanitize=address -fno-omit-frame-pointer
    validation_item "UndefinedBehaviorSanitizer" plain.cpp -fsanitize=undefined -fno-omit-frame-pointer
    validation_item "ThreadSanitizer" threads.cpp -fsanitize=thread -fno-omit-frame-pointer
    echo "- Debug-friendly sanitizer option:"
    echo "  - \`-fno-omit-frame-pointer\`"
    echo "- TSan cannot be combined with ASan in one build; the project uses separate"
    echo "  presets (\`asan-ubsan\`, \`tsan\`)."
    echo

    echo "## FreeBASIC"
    echo
    echo "- fbc (FreeBASIC compiler; not on PATH)"
    if [[ -x "$FBC" ]]; then
        echo "  - Path: \`$FBC\`"
        echo "  - Version: \`$(first_line "$FBC" -version)\`"
        if [[ -f "$FBC_TARBALL" ]]; then
            echo "  - Distribution tarball: \`$FBC_TARBALL\`,"
            echo "    SHA-256 \`$(sha256sum "$FBC_TARBALL" | cut -d' ' -f1)\`"
        fi
        echo "  - Project tools find it through \`GEF_FBC\`, falling back to"
        echo "    \`$FBC_DEFAULT\`."
        echo "  - Every invocation prints harmless \`libtinfo.so.5: no version information available\`"
        echo "    and \`\`Symbol \`ospeed' has different size\`\` loader warnings on stderr."
    else
        echo "  - Status: not available at \`$FBC\` (set \`GEF_FBC\`)"
    fi
    echo

    echo "## SQL"
    echo
    tool_section "sqls" sqls sqls --version
    echo

    echo "## Go"
    echo
    tool_section "Go" go go version
    echo

    echo "## Git"
    echo
    tool_section "Git" git git --version
    echo

    echo "## Executable search path"
    echo
    echo '```text'
    printf '%s\n' "$PATH" | tr ':' '\n'
    echo '```'
    echo

    echo "## Notes"
    echo
    echo "- This file describes only the \`$MACHINE_NAME\` development environment."
    echo "- Do not infer that paths, versions, package managers, or installed tools are identical on other machines."
    echo "- Prefer commands available through \`PATH\` rather than hard-coded absolute paths."
    echo "- The counterpart development machine may provide a different \`.omp/LOCAL_ENVIRONMENT.md\`."
} > "$LOCAL_ENV_FILE"

# ---------------------------------------------------------------------------
# Ensure the local environment file is ignored
# ---------------------------------------------------------------------------

IGNORE_ENTRY=".omp/LOCAL_ENVIRONMENT.md"

if ! git -C "$REPO_ROOT" check-ignore -q "$IGNORE_ENTRY" 2>/dev/null; then
    touch "$GITIGNORE"
    printf '\n%s\n' "$IGNORE_ENTRY" >> "$GITIGNORE"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo
echo "Local environment written:"
echo "  $LOCAL_ENV_FILE"
if [[ ! -f "$AGENTS_FILE" ]]; then
    echo "warning: $AGENTS_FILE does not exist; agents will not see the environment description"
elif ! grep -Fq "@LOCAL_ENVIRONMENT.md" "$AGENTS_FILE"; then
    echo "warning: $AGENTS_FILE does not include @LOCAL_ENVIRONMENT.md"
fi
echo
echo "Machine name: $MACHINE_NAME"
echo
echo "Git status:"
git -C "$REPO_ROOT" status --short -- \
    .omp/AGENTS.md \
    .omp/LOCAL_ENVIRONMENT.md \
    .gitignore
