# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.
"""Per-variable fingerprints of a T0 probe dump (M4 plan, D7).

``python3 -m harness.probe_fingerprints <capture-id> --name <golden-name> [--probe T0]``

Reads ``validation/reference_store/captures/<capture-id>/work/probes/<probe>.txt``, groups the
lines by NAME (the third field; the context of a T0 line is ``-``, so it has no spaces), and
writes ``Cpp_implementation/tests/golden/<golden-name>/<probe>.txt``: one row per variable,
``NAME LINE_COUNT FNV1A64_HEX``. The digest is FNV-1a 64 over every line's bytes plus ``\\n``.
The golden is recorded as derived from the capture (``derived.json``).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from harness.common import STORE_CAPTURES, HarnessError
from harness.golden import GOLDEN_DIR, write_derived

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
MASK64 = (1 << 64) - 1


@dataclass(frozen=True)
class Fingerprint:
    """One variable: its line count and FNV-1a 64 digest."""

    name: str
    lines: int
    fnv: int


def fnv1a64(lines: list[bytes]) -> int:
    """FNV-1a 64 over each line followed by a newline."""
    h = FNV_OFFSET
    for line in lines:
        for byte in line + b"\n":
            h = ((h ^ byte) * FNV_PRIME) & MASK64
    return h


def split_lines(data: bytes) -> list[bytes]:
    """Lines of ``data`` without their newlines (a final newline ends the last line)."""
    lines = data.split(b"\n")
    if lines and lines[-1] == b"":
        lines.pop()
    return lines


def fingerprints(data: bytes, probe: str) -> list[Fingerprint]:
    """Group the lines of a probe dump by NAME; a variable's lines must be contiguous."""
    groups: list[tuple[str, list[bytes]]] = []
    seen: set[str] = set()
    for raw in split_lines(data):
        fields = raw.split(b" ", 3)
        if len(fields) < 4 or fields[0] != probe.encode("ascii"):
            raise HarnessError(f"not a {probe} line: {raw[:80]!r}")
        if fields[1] != b"-":
            raise HarnessError(f"{probe} context must be '-', got {fields[1]!r}")
        name = fields[2].decode("ascii")
        if groups and groups[-1][0] == name:
            groups[-1][1].append(raw)
            continue
        if name in seen:
            raise HarnessError(f"variable {name} is not contiguous in {probe}")
        seen.add(name)
        groups.append((name, [raw]))
    return [Fingerprint(name, len(lines), fnv1a64(lines)) for name, lines in groups]


def render(capture_id: str, name: str, probe: str, rows: list[Fingerprint]) -> str:
    """The golden file text: a 3-line ``#`` header, then one row per variable."""
    header = [
        f"# Per-variable fingerprints of probe {probe} from reference-store capture {capture_id}.",
        "# Columns: NAME, line count, FNV-1a 64 (hex) over each line's bytes plus a newline.",
        f"# Generated by: python3 -m harness.probe_fingerprints {capture_id} --name {name} "
        f"--probe {probe}",
    ]
    body = [f"{row.name} {row.lines} {row.fnv:016x}" for row in rows]
    return "\n".join(header + body) + "\n"


def generate(capture_id: str, name: str, probe: str) -> Path:
    """Write the golden for one capture and record its derivation."""
    source = STORE_CAPTURES / capture_id / "work" / "probes" / f"{probe}.txt"
    if not source.is_file():
        raise HarnessError(f"missing probe dump {source}")
    rows = fingerprints(source.read_bytes(), probe)
    golden_dir = GOLDEN_DIR / name
    golden_dir.mkdir(parents=True, exist_ok=True)
    out = golden_dir / f"{probe}.txt"
    out.write_text(render(capture_id, name, probe, rows), encoding="ascii")
    tool = f"python3 -m harness.probe_fingerprints {capture_id} --name {name} --probe {probe}"
    write_derived(golden_dir, tool, [(capture_id, f"work/probes/{probe}.txt")])
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Fingerprint a T0 probe dump per variable.")
    parser.add_argument("capture_id")
    parser.add_argument("--name", required=True, help="golden directory name")
    parser.add_argument("--probe", default="T0")
    args = parser.parse_args()
    out = generate(args.capture_id, args.name, args.probe)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
