# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.
"""Per-variable fingerprints of a probe dump (M4 plan, D7).

``python3 -m harness.probe_fingerprints <capture-id> --name <golden-name> [--probe T0]
[--context CONTEXT]``

Reads ``validation/reference_store/captures/<capture-id>/work/probes/<probe>.txt``, keeps the
lines of one record (``CONTEXT``, see ``harness/PROBES.md``: ``-`` for T0, the default, or e.g.
``step=1 pass=- bin=- rec=1`` for P1; the lines of other records are skipped), groups them by
NAME (the field after the context), and writes
``Cpp_implementation/tests/golden/<golden-name>/<probe>.txt``: one row per variable,
``NAME LINE_COUNT FNV1A64_HEX``. The digest is FNV-1a 64 over every line's bytes plus ``\\n``.
The golden is recorded as derived from the capture (``derived.json``).
"""

from __future__ import annotations

import argparse
import shlex
from dataclasses import dataclass
from pathlib import Path

from harness.common import STORE_CAPTURES, HarnessError
from harness.golden import GOLDEN_DIR, write_derived

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
MASK64 = (1 << 64) - 1


@dataclass(frozen=True)
class Fingerprint:
    """One variable: its line count and FNV-1a 64 digest."""

    name: str
    lines: int
    fnv: int


def fnv1a64(lines: list[bytes]) -> int:
    """FNV-1a 64 over each line followed by a newline."""
    h = FNV_OFFSET
    for line in lines:
        for byte in line + b"\n":
            h = ((h ^ byte) * FNV_PRIME) & MASK64
    return h


def split_lines(data: bytes) -> list[bytes]:
    """Lines of ``data`` without their newlines (a final newline ends the last line)."""
    lines = data.split(b"\n")
    if lines and lines[-1] == b"":
        lines.pop()
    return lines


def fingerprints(data: bytes, probe: str, context: str = "-") -> list[Fingerprint]:
    """Group the lines of one record of a probe dump by NAME; a variable's lines must be
    contiguous. Lines of other records (another context) are skipped."""
    probe_prefix = probe.encode("ascii") + b" "
    prefix = probe_prefix + context.encode("ascii") + b" "
    groups: list[tuple[str, list[bytes]]] = []
    seen: set[str] = set()
    for raw in split_lines(data):
        if not raw.startswith(probe_prefix):
            raise HarnessError(f"not a {probe} line: {raw[:80]!r}")
        if not raw.startswith(prefix):
            continue
        fields = raw[len(prefix) :].split(b" ", 1)
        if len(fields) < 2:
            raise HarnessError(f"malformed {probe} line: {raw[:80]!r}")
        name = fields[0].decode("ascii")
        if groups and groups[-1][0] == name:
            groups[-1][1].append(raw)
            continue
        if name in seen:
            raise HarnessError(f"variable {name} is not contiguous in {probe}")
        seen.add(name)
        groups.append((name, [raw]))
    if not groups:
        raise HarnessError(f"no {probe} record with context {context!r}")
    return [Fingerprint(name, len(lines), fnv1a64(lines)) for name, lines in groups]


def _tool(capture_id: str, name: str, probe: str, context: str) -> str:
    tool = f"python3 -m harness.probe_fingerprints {capture_id} --name {name} --probe {probe}"
    if context != "-":
        tool += f" --context {shlex.quote(context)}"
    return tool


def render(capture_id: str, name: str, probe: str, rows: list[Fingerprint], context: str) -> str:
    """The golden file text: a 3-line ``#`` header, then one row per variable."""
    record = "" if context == "-" else f" (record {context})"
    header = [
        f"# Per-variable fingerprints of probe {probe}{record} from reference-store capture "
        f"{capture_id}.",
        "# Columns: NAME, line count, FNV-1a 64 (hex) over each line's bytes plus a newline.",
        f"# Generated by: {_tool(capture_id, name, probe, context)}",
    ]
    body = [f"{row.name} {row.lines} {row.fnv:016x}" for row in rows]
    return "\n".join(header + body) + "\n"


def generate(capture_id: str, name: str, probe: str, context: str = "-") -> Path:
    """Write the golden for one capture and record its derivation."""
    source = STORE_CAPTURES / capture_id / "work" / "probes" / f"{probe}.txt"
    if not source.is_file():
        raise HarnessError(f"missing probe dump {source}")
    rows = fingerprints(source.read_bytes(), probe, context)
    golden_dir = GOLDEN_DIR / name
    golden_dir.mkdir(parents=True, exist_ok=True)
    out = golden_dir / f"{probe}.txt"
    out.write_text(render(capture_id, name, probe, rows, context), encoding="ascii")
    write_derived(
        golden_dir,
        _tool(capture_id, name, probe, context),
        [(capture_id, f"work/probes/{probe}.txt")],
    )
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Fingerprint one record of a probe dump.")
    parser.add_argument("capture_id")
    parser.add_argument("--name", required=True, help="golden directory name")
    parser.add_argument("--probe", default="T0")
    parser.add_argument("--context", default="-", help="record context ('-' for T0)")
    args = parser.parse_args()
    out = generate(args.capture_id, args.name, args.probe, args.context)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
