# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.
"""Inventory of the Print Using templates and Format patterns used by GEF (M3.6b).

Usage (from the repository root)::

    python3 -m tools.fbsrc.fb_templates

Reads ``build/fbsrc/ba9f0aa/src/GEF.c`` (emitted by fbc; see ``tools.fbsrc.fbline``) and
writes ``Cpp_implementation/src/fbrt/TEMPLATES.md``. Locations come from fbc's ``#line``
directives, so every row names the BASIC file and line of the first call.

Exit status: 0 on success, 2 when the generated C is missing.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from tools.fbsrc.common import FbsrcError

REPO_ROOT = Path(__file__).resolve().parents[2]
GEF_C = REPO_ROOT / "build" / "fbsrc" / "ba9f0aa" / "src" / "GEF.c"
OUT_MD = REPO_ROOT / "Cpp_implementation" / "src" / "fbrt" / "TEMPLATES.md"

LINE_RE = re.compile(r'^\s*#line (\d+) "([^"]+)"')
INIT_RE = re.compile(r'(vr\$\d+) = fb_StrAllocTempDescZEx\( \(char\*\)"([^"]*)"')
PRINT_INIT_RE = re.compile(r"fb_PrintUsingInit\( \(FBSTRING\*\)(vr\$\d+) \)")
ASSIGN_RE = re.compile(r'fb_StrAssign\( \(void\*\)&(TMP\$\d+\$\d+), -1ll, \(void\*\)"([^"]*)"')
FORMAT_RE = re.compile(r"fb_StrFormat\( .*?&(TMP\$\d+\$\d+) \)")
ITEM_RE = re.compile(r"fb_PrintUsing(Single|Double|Longint|Str)\(")
END_RE = re.compile(r"fb_PrintUsingEnd\(")


@dataclass
class Scan:
    """Template and pattern uses, keyed by text, in order of first appearance."""

    print_uses: dict[str, list[str]] = field(default_factory=dict)
    print_items: dict[str, set[str]] = field(default_factory=dict)
    format_uses: dict[str, list[str]] = field(default_factory=dict)
    items: Counter[str] = field(default_factory=Counter)


def scan(lines: list[str]) -> Scan:
    """Collect every template, pattern and item call with its BASIC location."""
    result = Scan()
    where = "?"
    init_text: dict[str, str] = {}
    format_text: dict[str, str] = {}
    current: str | None = None  # template of the Print Using statement being scanned
    current_items: list[str] = []
    for raw in lines:
        if (loc := LINE_RE.match(raw)) is not None:
            where = f"{Path(loc.group(2)).name}:{loc.group(1)}"
            continue
        if (init := INIT_RE.search(raw)) is not None:
            init_text[init.group(1)] = init.group(2)
        if (use := PRINT_INIT_RE.search(raw)) is not None:
            current = init_text.get(use.group(1), "?")
            current_items = []
            result.print_uses.setdefault(current, []).append(where)
        if (assign := ASSIGN_RE.search(raw)) is not None:
            format_text[assign.group(1)] = assign.group(2)
        if (fmt := FORMAT_RE.search(raw)) is not None:
            pattern = format_text.get(fmt.group(1), "?")
            result.format_uses.setdefault(pattern, []).append(where)
        # Prototypes sit at column 0 as "int32 fb_PrintUsing...( ... );".
        if not raw.startswith("int32 fb_"):
            for item in ITEM_RE.finditer(raw):
                result.items[item.group(1)] += 1
                current_items.append(item.group(1))
            if current is not None and END_RE.search(raw) is not None:
                result.print_items.setdefault(current, set()).add(" ".join(current_items))
                current = None
    return result


def table(
    header: str, uses: dict[str, list[str]], items: dict[str, set[str]] | None = None
) -> list[str]:
    """Markdown table rows: text, number of uses, first BASIC location (and item types)."""
    rows = [header, "| --- | ---: | --- |" + (" --- |" if items is not None else "")]
    for text, locs in uses.items():
        row = f"| `{text}` | {len(locs)} | {locs[0]} |"
        if items is not None:
            row += " " + "; ".join(sorted(items.get(text, set()))) + " |"
        rows.append(row)
    return rows


def render(result: Scan) -> str:
    """Build the TEMPLATES.md document."""
    items = result.items
    lines = [
        "# GEF Print Using templates and Format patterns",
        "",
        "Generated by `python3 -m tools.fbsrc.fb_templates` from `build/fbsrc/ba9f0aa/src/GEF.c`;"
        " do not edit by hand.",
        "",
        "## Print Using",
        "",
        f"Item calls: Single {items['Single']}, Double {items['Double']}, "
        f"Longint {items['Longint']}, Str {items['Str']}.",
        "",
    ]
    lines += table(
        "| Template | Statements | First use | Items per statement |",
        result.print_uses,
        result.print_items,
    )
    lines += [
        "",
        "## Format",
        "",
    ]
    lines += table("| Pattern | Calls | First use |", result.format_uses)
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write TEMPLATES.md from the generated GEF.c."""
    try:
        if not GEF_C.is_file():
            raise FbsrcError(f"missing {GEF_C}; emit it with tools.fbsrc.fbline first")
        text = GEF_C.read_text(encoding="utf-8")
    except (FbsrcError, OSError) as exc:
        print(f"fb_templates: {exc}", file=sys.stderr)
        return 2
    OUT_MD.write_text(render(scan(text.splitlines())), encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
