# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.
"""Generate the DATA sources behind ``gef::data::ProgramData`` (M4.2).

Usage (from the repository root)::

    taskset -c 0-9 python3 -m tools.fbsrc.gen_gef_data                 # regenerate
    taskset -c 0-9 python3 -m tools.fbsrc.gen_gef_data --check         # exit 1 when stale
    taskset -c 0-9 python3 -m tools.fbsrc.gen_gef_data --fingerprints  # write the golden

For each of the seven nuclide-data variants (the ``m4-*`` patch sets) the C emitted by fbc is
parsed. Its DATA tables form one chain through their ``label$N`` links; each table holds the
item texts fbc stores, decoded from the C string literals. A table is named after the BASIC
``Restore`` label that points at it: the ``#line`` directive before each ``fb_DataRestore`` call
gives the BASIC file and line. A block identical in every variant is emitted once.

The generated sources go to ``Cpp_implementation/src/data/generated/``; they are formatted with
the repository's ``.clang-format`` (``clang-format`` must be on ``PATH``). ``--fingerprints``
writes ``Cpp_implementation/tests/golden/m4-datachain/fingerprints.txt`` and cross-checks every
item against the reference-store captures.

Exit status: 0 on success, 1 when ``--check`` finds stale generated files, 2 on a failure.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from collections import Counter
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from harness.build import materialize_patch_dir
from harness.golden import write_derived
from tools.fbsrc.common import FbsrcError, display_path, read_source_lines
from tools.fbsrc.emit_c import Emission, emit
from tools.toolchain.fbc import REPO_ROOT

CPP_DATA_DIR = REPO_ROOT / "Cpp_implementation" / "src" / "data"
GENERATED_DIR = CPP_DATA_DIR / "generated"
GOLDEN_PATH = REPO_ROOT / "Cpp_implementation" / "tests" / "golden" / "m4-datachain"
GOLDEN_FILE = GOLDEN_PATH / "fingerprints.txt"
CAPTURES_DIR = REPO_ROOT / "validation" / "reference_store" / "captures"
GENERATOR = "python3 -m tools.fbsrc.gen_gef_data"

LICENCE_LINES = (
    "// SPDX-License-Identifier: GPL-3.0-or-later",
    "// Copyright (C) 2026 Aurora Jahan",
    "// Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.",
    "// Ported from GEF 2025/1.2, Copyright (C) 2009-2025 Karl-Heinz Schmidt and Beatriz Jurado.",
    f"// Generated by {GENERATOR}; do not edit.",
)

# Characters per string-literal line of a block's text (before C escaping).
_LITERAL_CHUNK = 80
# Most bytes in one DATA block's text: a longer table is split, since a C++ string literal may
# not exceed 65536 characters (clang -Woverlength-strings).
_CHUNK_BYTES = 32768
_FNV_OFFSET = 0xCBF29CE484222325
_FNV_PRIME = 0x100000001B3
_MASK64 = (1 << 64) - 1


@dataclass(frozen=True)
class Variant:
    """One nuclide-data variant: its patch set, its ISOSOURCE and its datachain capture."""

    key: str
    enumerator: str
    patch_set: str
    isosource: str
    capture: str


VARIANTS: tuple[Variant, ...] = (
    Variant("jeff33", "Jeff33", "m4-jeff33", "JEFF-3.3", "m4-t0-jeff33"),
    Variant("jeff311", "Jeff311", "m4-jeff311", "JEFF-3.1.1", "m4-t0-jeff311"),
    Variant("nubase2016", "Nubase2016", "m4-nubase2016", "NUBASE-2016", "m4-t0-nubase2016"),
    Variant("nubase2020", "Nubase2020", "m4-nubase2020", "NUBASE-2020", "m4-datachain-nubase2020"),
    Variant("legacy-x", "LegacyX", "m4-legacy-x", "NucPropx", "m4-t0-legacy-x"),
    Variant("legacy-mf", "LegacyMf", "m4-legacy-mf", "NucPropmf", "m4-t0-legacy-mf"),
    Variant("legacy-f", "LegacyF", "m4-legacy-f", "NucPropf", "m4-t0-legacy-f"),
)

# One C string-literal character: a plain printable character (not `\` or `"`), or an escape.
_C_TOKEN = re.compile(
    r"\\(?:x([0-9A-Fa-f]+)|([0-7]{1,3})|([ntr\\\"'?abfv]))|([\x20\x21\x23-\x5b\x5d-\x7e])"
)
_SIMPLE_ESCAPES = {
    "n": 0x0A,
    "t": 0x09,
    "r": 0x0D,
    "\\": 0x5C,
    '"': 0x22,
    "'": 0x27,
    "?": 0x3F,
    "a": 0x07,
    "b": 0x08,
    "f": 0x0C,
    "v": 0x0B,
}
_ENTRY_SOURCE = r'\{ \(int16\)(-?\d+), \(void\*\)(?:"((?:[^"\\]|\\.)*)"|label\$(\d+)|0ull) \}'
_ENTRY = re.compile(_ENTRY_SOURCE)
_TABLE_BODY = re.compile(rf"{_ENTRY_SOURCE}(?:, {_ENTRY_SOURCE})*")
_DECL = re.compile(r"static struct \$14__FB_DATADESC\$ label\$(\d+)\[(\d+)\] = \{ (.*) \};")
_LINE_DIRECTIVE = re.compile(r'\s*#line\s+(\d+)\s+"([^"]*)"')
_RESTORE_CALL = re.compile(r"fb_DataRestore\( \(void\*\)label\$(\d+) \);")
_RESTORE_STMT = re.compile(r"\s*restore\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.IGNORECASE)
_LABEL = re.compile(r"[A-Z][A-Z0-9_]*")


def decode_c_string(body: str) -> bytes:
    """The bytes of the C string literal ``body`` (the text between the quotes).

    Accepts the escapes fbc can emit: ``\\xHH`` (all hex digits, as C reads them), octal of
    one to three digits, and the simple escapes. Anything else is an error.
    """
    out = bytearray()
    pos = 0
    for match in _C_TOKEN.finditer(body):
        if match.start() != pos:
            raise FbsrcError(f"unsupported C string syntax at offset {pos} in {body!r}")
        pos = match.end()
        hex_digits, octal_digits, simple, plain = match.groups()
        if plain is not None:
            out.append(ord(plain))
        elif hex_digits is not None:
            out.append(_byte_value(int(hex_digits, 16), body))
        elif octal_digits is not None:
            out.append(_byte_value(int(octal_digits, 8), body))
        else:
            out.append(_SIMPLE_ESCAPES[simple])
    if pos != len(body):
        raise FbsrcError(f"unsupported C string syntax at offset {pos} in {body!r}")
    return bytes(out)


def _byte_value(value: int, body: str) -> int:
    if value > 0xFF:
        raise FbsrcError(f"C character escape out of range in {body!r}")
    return value


@dataclass(frozen=True)
class DataTable:
    """One DATA table of the emitted C: its items and the table its link points at."""

    index: int
    items: tuple[bytes, ...]
    link: int | None


def parse_tables(text: str) -> dict[int, DataTable]:
    """Every ``static struct $14__FB_DATADESC$ label$N[...]`` declaration in the emitted C."""
    tables: dict[int, DataTable] = {}
    for line in text.split("\n"):
        decl = _DECL.fullmatch(line)
        if decl is None:
            continue
        index = int(decl.group(1))
        count = int(decl.group(2))
        body = decl.group(3)
        if index in tables:
            raise FbsrcError(f"DATA table label${index} is declared twice")
        if _TABLE_BODY.fullmatch(body) is None:
            raise FbsrcError(f"unexpected entries in DATA table label${index}")
        entries = [(int(e.group(1)), e.group(2), e.group(3)) for e in _ENTRY.finditer(body)]
        if len(entries) != count:
            raise FbsrcError(
                f"DATA table label${index} declares {count} entries, has {len(entries)}"
            )
        items: list[bytes] = []
        for length, string, link in entries[:-1]:
            if string is None or link is not None or length < 0:
                raise FbsrcError(f"DATA table label${index} has an entry that is not an item")
            data = decode_c_string(string)
            if len(data) != length:
                raise FbsrcError(
                    f"DATA table label${index}: item length {length} != decoded {len(data)}"
                )
            items.append(data)
        last_length, last_string, last_link = entries[-1]
        if last_length != -1 or last_string is not None:
            raise FbsrcError(f"DATA table label${index} does not end in a link entry")
        tables[index] = DataTable(
            index, tuple(items), None if last_link is None else int(last_link)
        )
    if not tables:
        raise FbsrcError("no DATA tables found in the emitted C")
    return tables


def chain_order(tables: Mapping[int, DataTable]) -> list[DataTable]:
    """The tables in chain order: the one no link points to, then each link in turn."""
    inbound = Counter(t.link for t in tables.values() if t.link is not None)
    for target, count in inbound.items():
        if count > 1 or target not in tables:
            raise FbsrcError(f"DATA link to label${target} is shared or dangling")
    heads = [index for index in tables if inbound[index] == 0]
    if len(heads) != 1:
        raise FbsrcError(f"DATA chain has {len(heads)} heads, expected 1")
    chain: list[DataTable] = []
    current: int | None = heads[0]
    while current is not None:
        table = tables.get(current)
        if table is None or len(chain) == len(tables):
            raise FbsrcError("DATA chain is cyclic or dangling")
        chain.append(table)
        current = table.link
    if len(chain) != len(tables):
        raise FbsrcError(f"DATA chain visits {len(chain)} of {len(tables)} tables")
    return chain


def restore_names(text: str, src_dir: Path) -> tuple[dict[int, str], int]:
    """The Restore label of each table that a ``Restore`` names, and the number of calls.

    The BASIC line is read from ``src_dir`` (the file's basename in the ``#line`` directive).
    """
    names: dict[int, str] = {}
    owners: dict[str, int] = {}
    sources: dict[Path, list[str]] = {}
    location: tuple[int, str] | None = None
    calls = 0
    for line in text.split("\n"):
        directive = _LINE_DIRECTIVE.match(line)
        if directive is not None:
            location = (int(directive.group(1)), directive.group(2))
            continue
        call = _RESTORE_CALL.search(line)
        if call is None:
            continue
        calls += 1
        if location is None:
            raise FbsrcError("fb_DataRestore call before any #line directive")
        basic_line, basic_name = location
        path = src_dir / Path(basic_name).name
        if path not in sources:
            try:
                sources[path] = read_source_lines(path)
            except OSError as error:
                raise FbsrcError(f"cannot read BASIC source {path}: {error}") from error
        lines = sources[path]
        if not 1 <= basic_line <= len(lines):
            raise FbsrcError(f"#line {basic_line} is past the end of {path.name}")
        statement = _RESTORE_STMT.match(lines[basic_line - 1])
        if statement is None:
            raise FbsrcError(f"{path.name}:{basic_line} is not a Restore statement")
        name = statement.group(1).upper()
        index = int(call.group(1))
        if names.setdefault(index, name) != name:
            raise FbsrcError(f"DATA table label${index} is restored under two names")
        if owners.setdefault(name, index) != index:
            raise FbsrcError(f"Restore label {name} names two DATA tables")
    return names, calls


@dataclass(frozen=True)
class Block:
    """One DATA block: some items of one DATA table, at most ``_CHUNK_BYTES`` bytes.

    ``name`` is the table's Restore label (``None`` if it has none); ``part`` is the block's
    index within its table.
    """

    name: str | None
    items: tuple[bytes, ...]
    part: int = 0


@dataclass(frozen=True)
class VariantData:
    """One variant's chain of blocks and its Restore labels, in chain order."""

    variant: Variant
    blocks: tuple[Block, ...]
    labels: tuple[tuple[str, int], ...]
    restore_calls: int


def split_table(name: str | None, items: tuple[bytes, ...]) -> list[Block]:
    """Split a table's items into blocks of at most ``_CHUNK_BYTES`` bytes, newlines included."""
    groups: list[list[bytes]] = [[]]
    size = 0
    for item in items:
        cost = len(item) + 1
        if cost > _CHUNK_BYTES:
            raise FbsrcError(f"DATA item of {len(item)} bytes does not fit one block")
        if groups[-1] and size + cost > _CHUNK_BYTES:
            groups.append([])
            size = 0
        groups[-1].append(item)
        size += cost
    return [Block(name, tuple(group), part) for part, group in enumerate(groups)]


def _part_suffix(block: Block) -> str:
    """``_<part>`` for the continuation blocks of a long table, else nothing."""
    return f"_{block.part}" if block.part else ""


def build_variant(variant: Variant, emission: Emission) -> VariantData:
    """Parse the emitted C of one variant and check it against the ISOSOURCE literal."""
    text = emission.gef_c.read_text(encoding="utf-8")
    tables = parse_tables(text)
    chain = chain_order(tables)
    names, calls = restore_names(text, emission.src_dir)
    unknown = sorted(set(names) - set(tables))
    if unknown:
        raise FbsrcError(f"Restore targets are not DATA tables: {unknown}")
    if f'"{variant.isosource}"' not in text:
        raise FbsrcError(f"ISOSOURCE {variant.isosource!r} is not in the emitted C")
    blocks: list[Block] = []
    for table in chain:
        for item in table.items:
            if not all(0x20 <= byte <= 0x7E for byte in item):
                raise FbsrcError(f"DATA item {item!r} is not printable ASCII")
        name = names.get(table.index)
        if name is not None and _LABEL.fullmatch(name) is None:
            raise FbsrcError(f"Restore label {name!r} is not a plain identifier")
        blocks.extend(split_table(name, table.items))
    labels = tuple(
        sorted(
            (block.name, position)
            for position, block in enumerate(blocks)
            if block.name and not block.part
        )
    )
    return VariantData(variant, tuple(blocks), labels, calls)


def item_hex(item: bytes) -> str:
    """An item as the datachain probe writes it: uppercase hex, ``-`` when empty."""
    return item.hex().upper() if item else "-"


def fingerprint(items: Iterable[bytes]) -> int:
    """FNV-1a 64 over each item's ``item_hex`` text followed by a newline."""
    digest = _FNV_OFFSET
    for item in items:
        for byte in f"{item_hex(item)}\n".encode("ascii"):
            digest = ((digest ^ byte) * _FNV_PRIME) & _MASK64
    return digest


def shared_symbols(variants: Sequence[VariantData]) -> dict[Block, str]:
    """C++ symbols for the blocks every variant has, in first-variant chain order."""
    common = set(variants[0].blocks)
    for data in variants[1:]:
        common &= set(data.blocks)
    symbols: dict[Block, str] = {}
    unnamed = 0
    for block in variants[0].blocks:
        if block not in common or block in symbols:
            continue
        if block.name is None:
            unnamed += 1
            symbol = f"shared_unrestored_{unnamed}"
        else:
            symbol = f"shared_{block.name.lower()}{_part_suffix(block)}"
        symbols[block] = symbol
    if len(set(symbols.values())) != len(symbols):
        raise FbsrcError("shared block symbols collide")
    return symbols


def own_symbols(data: VariantData, shared: Mapping[Block, str]) -> dict[Block, str]:
    """C++ symbols for the blocks one variant has alone."""
    symbols: dict[Block, str] = {}
    unnamed = 0
    for block in data.blocks:
        if block in shared or block in symbols:
            continue
        if block.name is None:
            unnamed += 1
            symbols[block] = f"own_unrestored_{unnamed}"
        else:
            symbols[block] = f"own_{block.name.lower()}{_part_suffix(block)}"
    return symbols


def _c_escape(byte: int) -> str:
    if byte == 0x0A:
        return "\\n"
    if byte in (0x22, 0x3F, 0x5C):
        return "\\" + chr(byte)
    return chr(byte)


def render_block(symbol: str, block: Block) -> list[str]:
    """The definition of one ``DataBlock``: the items as ``\\n``-terminated text."""
    raw = b"".join(item + b"\n" for item in block.items)
    literals = [
        '"' + "".join(_c_escape(byte) for byte in raw[start : start + _LITERAL_CHUNK]) + '"'
        for start in range(0, len(raw), _LITERAL_CHUNK)
    ] or ['""']
    text_lines = [f"    .text = {literals[0]}", *(f"        {literal}" for literal in literals[1:])]
    text_lines[-1] += ","
    lines = [f"DataBlock const {symbol}{{", *text_lines]
    lines.extend([f"    .items = {len(block.items)},", "};", ""])
    return lines


def render_shared(symbols: Mapping[Block, str]) -> str:
    """``shared_tables.cpp``: every block that all variants share."""
    lines = [
        '#include "data/generated/tables.hpp"',
        "",
        "namespace gef::data::generated {",
        "",
    ]
    for block, symbol in symbols.items():
        lines.extend(render_block(symbol, block))
    lines.append("}  // namespace gef::data::generated")
    return _file(lines)


def render_variant(data: VariantData, shared: Mapping[Block, str]) -> str:
    """``variant_<key>.cpp``: the variant's own block, its chain and its labels."""
    own = own_symbols(data, shared)
    symbol_of = {**shared, **own}
    key = data.variant.key.replace("-", "_")
    lines = [
        '#include "data/generated/tables.hpp"',
        "",
        "#include <array>",
        "",
        "namespace gef::data::generated {",
        "",
        "namespace {",
        "",
    ]
    for block, symbol in own.items():
        lines.extend(render_block(symbol, block))
    lines.append("// Only the addresses of blocks in other translation units are taken here.")
    lines.append("// NOLINTBEGIN(cppcoreguidelines-interfaces-global-init)")
    lines.append(f"std::array<DataBlock const*, {len(data.blocks)}> const chain{{")
    lines.extend(f"    &{symbol_of[block]}," for block in data.blocks)
    lines.extend(["};", "// NOLINTEND(cppcoreguidelines-interfaces-global-init)", ""])
    lines.append(f"std::array<LabelEntry, {len(data.labels)}> const labels{{")
    lines.extend(
        f'    LabelEntry{{.name = "{name}", .block = {position}}},'
        for name, position in data.labels
    )
    lines.extend(["};", "", "}  // namespace", ""])
    lines.extend(
        [
            f"VariantTables const variant_{key}{{",
            f'    .isosource = "{data.variant.isosource}",',
            "    .chain = chain,",
            "    .labels = labels,",
            "};",
            "",
            "}  // namespace gef::data::generated",
        ]
    )
    return _file(lines)


def render_tables_header(shared: Mapping[Block, str], variants: Sequence[VariantData]) -> str:
    """``tables.hpp``: the declarations ``shared_tables.cpp`` and the variant files define."""
    lines = [
        "#pragma once",
        "",
        '#include "data/data_block.hpp"',
        "",
        "namespace gef::data::generated {",
        "",
        "// Blocks that every variant shares (defined in shared_tables.cpp).",
    ]
    lines.extend(f"extern DataBlock const {symbol};" for symbol in shared.values())
    lines.extend(
        ["", "// One table of chain and labels per variant (defined in variant_<key>.cpp)."]
    )
    lines.extend(
        f"extern VariantTables const variant_{data.variant.key.replace('-', '_')};"
        for data in variants
    )
    lines.extend(["", "}  // namespace gef::data::generated"])
    return _file(lines)


def _file(body: Sequence[str]) -> str:
    """Prefix the licence and generator lines; drop trailing blank lines."""
    lines = [*LICENCE_LINES, "", *body]
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def format_cpp(text: str, path: Path) -> str:
    """Format generated C++ with the repository's ``.clang-format``."""
    clang_format = shutil.which("clang-format")
    if clang_format is None:
        raise FbsrcError("clang-format is required to format the generated C++ (see scripts/ci.sh)")
    result = subprocess.run(
        [clang_format, f"--assume-filename={display_path(path)}"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
        cwd=REPO_ROOT,
    )
    if result.returncode != 0:
        raise FbsrcError(f"clang-format failed on {path.name}: {result.stderr.strip()}")
    return result.stdout


def generated_files(variants: Sequence[VariantData]) -> dict[Path, str]:
    """Every generated file, keyed by path, already formatted."""
    shared = shared_symbols(variants)
    files: dict[Path, str] = {
        GENERATED_DIR / "tables.hpp": render_tables_header(shared, variants),
        GENERATED_DIR / "shared_tables.cpp": render_shared(shared),
    }
    for data in variants:
        key = data.variant.key.replace("-", "_")
        files[GENERATED_DIR / f"variant_{key}.cpp"] = render_variant(data, shared)
    return {path: format_cpp(text, path) for path, text in files.items()}


def load_variants() -> list[VariantData]:
    """Emit each variant's C (cached by fbc's emission store) and build its data."""
    loaded: list[VariantData] = []
    for variant in VARIANTS:
        patch_dir = materialize_patch_dir(variant.patch_set)
        loaded.append(build_variant(variant, emit(patch_dir=patch_dir)))
    return loaded


def check_capture(data: VariantData) -> int:
    """Compare every item with the reference-store datachain probe; return the item count."""
    path = CAPTURES_DIR / data.variant.capture / "work" / "probes" / "datachain.txt"
    try:
        lines = path.read_text(encoding="ascii").split("\n")
    except OSError as error:
        raise FbsrcError(f"cannot read datachain capture {path}: {error}") from error
    expected = [item_hex(item) for block in data.blocks for item in block.items]
    count = len(expected)
    if lines[:count] != expected:
        position = next(
            (i for i, (a, b) in enumerate(zip(lines, expected, strict=False)) if a != b),
            min(len(lines), count),
        )
        got = lines[position] if position < len(lines) else "<end of capture>"
        raise FbsrcError(
            f"{data.variant.key}: item {position} is {got!r} in the capture, "
            f"{expected[position]!r} from the chain"
        )
    if any(line != "-" for line in lines[count:] if line):
        raise FbsrcError(f"{data.variant.key}: capture has items past the chain's {count}")
    return count


def write_fingerprints(variants: Sequence[VariantData]) -> None:
    """Write the golden fingerprints after checking each item against the captures."""
    lines = [
        "# FNV-1a 64 over the DATA items of each variant: per item its uppercase hex bytes",
        "# ('-' when empty) and a newline. Columns: variant, item count, digest (hex).",
        f"# Generated by `{GENERATOR} --fingerprints`; do not edit by hand.",
    ]
    for data in variants:
        items = [item for block in data.blocks for item in block.items]
        check_capture(data)
        lines.append(f"{data.variant.key} {len(items)} {fingerprint(items):016x}")
    GOLDEN_PATH.mkdir(parents=True, exist_ok=True)
    GOLDEN_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    write_derived(
        GOLDEN_PATH,
        f"{GENERATOR} --fingerprints",
        [(data.variant.capture, "work/probes/datachain.txt") for data in variants],
    )


def summary(variants: Sequence[VariantData]) -> list[str]:
    """One line per variant, plus the sharing totals."""
    shared = shared_symbols(variants)
    lines: list[str] = []
    for data in variants:
        items = sum(len(block.items) for block in data.blocks)
        tables = sum(1 for block in data.blocks if block.part == 0)
        unrestored = sum(1 for block in data.blocks if block.name is None and block.part == 0)
        lines.append(
            f"{data.variant.key}: {tables} tables in {len(data.blocks)} blocks, "
            f"{len(data.labels)} restore labels ({data.restore_calls} calls), "
            f"{unrestored} unrestored, {items} items"
        )
    shared_items = sum(len(block.items) for block in shared)
    lines.append(f"shared: {len(shared)} blocks, {shared_items} items")
    return lines


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate, check, or write the fingerprint golden."""
    parser = argparse.ArgumentParser(description="Generate the ProgramData DATA sources (M4.2).")
    parser.add_argument("--check", action="store_true", help="fail when the sources are stale")
    parser.add_argument("--fingerprints", action="store_true", help="write the golden fingerprints")
    args = parser.parse_args(argv)
    try:
        variants = load_variants()
        if args.fingerprints:
            write_fingerprints(variants)
            print(f"wrote {display_path(GOLDEN_FILE)}")
            return 0
        files = generated_files(variants)
        if args.check:
            stale = [
                display_path(path)
                for path, text in files.items()
                if not path.is_file() or path.read_text(encoding="utf-8") != text
            ]
            extra = (
                [display_path(p) for p in GENERATED_DIR.iterdir() if p not in files]
                if GENERATED_DIR.is_dir()
                else []
            )
            for name in [*stale, *extra]:
                print(f"stale: {name}", file=sys.stderr)
            return 1 if stale or extra else 0
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        for path, text in files.items():
            path.write_text(text, encoding="utf-8")
            print(f"wrote {display_path(path)} ({len(text)} bytes)")
        for line in summary(variants):
            print(line)
    except FbsrcError as error:
        print(f"gen_gef_data: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
