# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.
#
# Build-time script (cmake -P): writes a C++ source defining gef::app::git_revision() from
# `git describe --always --dirty` of the repository at GEF_SOURCE_DIR. Runs on every build;
# the output file is only rewritten when the revision changes, so an unchanged revision
# causes no recompilation.
#
# Inputs: GEF_SOURCE_DIR, GEF_OUTPUT_FILE, GEF_GIT_EXECUTABLE (may be empty or *-NOTFOUND).
# The revision is "unknown" only when GEF_SOURCE_DIR is not inside a git checkout.

foreach(var IN ITEMS GEF_SOURCE_DIR GEF_OUTPUT_FILE)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "GefGitRevision.cmake: ${var} is not set")
    endif()
endforeach()

set(revision "unknown")
if(GEF_GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GEF_GIT_EXECUTABLE}" rev-parse --is-inside-work-tree
        WORKING_DIRECTORY "${GEF_SOURCE_DIR}"
        RESULT_VARIABLE inside_result
        OUTPUT_VARIABLE inside_output
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(inside_result EQUAL 0 AND inside_output STREQUAL "true")
        execute_process(
            COMMAND "${GEF_GIT_EXECUTABLE}" describe --always --dirty
            WORKING_DIRECTORY "${GEF_SOURCE_DIR}"
            RESULT_VARIABLE describe_result
            OUTPUT_VARIABLE describe_output
            ERROR_VARIABLE describe_error
            OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT describe_result EQUAL 0 OR describe_output STREQUAL "")
            message(FATAL_ERROR "git describe --always --dirty failed in ${GEF_SOURCE_DIR}: "
                                "${describe_error}")
        endif()
        set(revision "${describe_output}")
    endif()
elseif(EXISTS "${GEF_SOURCE_DIR}/.git")
    message(FATAL_ERROR "${GEF_SOURCE_DIR} is a git checkout but git was not found; "
                        "install git so gef --version can report the revision")
endif()

set(content "// Generated by Cpp_implementation/cmake/GefGitRevision.cmake. Do not edit.
#include \"app/build_info.hpp\"

namespace gef::app {

std::string_view git_revision() noexcept {
    return \"${revision}\";
}

} // namespace gef::app
")

set(staging_file "${GEF_OUTPUT_FILE}.tmp")
file(WRITE "${staging_file}" "${content}")
# configure_file(COPYONLY) leaves the output untouched when the content is unchanged.
configure_file("${staging_file}" "${GEF_OUTPUT_FILE}" COPYONLY)
file(REMOVE "${staging_file}")
