# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Aurora Jahan
# Licensed under the GNU GPL v3 or later, WITHOUT ANY WARRANTY; see LICENSE.txt.

add_subdirectory(src/fbrt)
add_subdirectory(src/util)
add_subdirectory(src/data)
add_subdirectory(src/params)
add_subdirectory(src/app)
add_subdirectory(tests)
